#ifndef DEVICETAKSPRIORITIES_H
#define DEVICETAKSPRIORITIES_H 

#define DEVICE_TASKPRIORITIES_DEVICEOTA         17 
// #define DEVICE_TASKPRIORITIES_CONNECTION        18 

#define DEVICE_TASKPRIORITIES_BUTTON            17 

#define DEVICE_TASKPRIORITIES_SERIAL            16

#define DEVICE_TASKPRIORITIES_CONFIGURATION     17

#define DEVICE_TASKPRIORITIES_LED_STATUS        16  
#define DEVICE_TASKPRIORITIES_WIFI              18
#define DEVICE_TASKPRIORITIES_MQTT              18

#define DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS        17 
#define DEVICE_TASKPRIORITIES_RELAY_GREEN_ACTIVATE      DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS
#define DEVICE_TASKPRIORITIES_RELAY_ORANGE_ACTIVATE     DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS
#define DEVICE_TASKPRIORITIES_RELAY_RED_ACTIVATE        DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS
#define DEVICE_TASKPRIORITIES_RELAY_CANCEL_ACTIVATE     DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS 


#endif