#ifndef DEVICETAKSPRIORITIES_H
#define DEVICETAKSPRIORITIES_H 

#define DEVICE_TASKPRIORITIES_DEVICEOTA         2  

#define DEVICE_TASKPRIORITIES_BUTTON            4  

#define DEVICE_TASKPRIORITIES_CONFIGURATION     1

#define DEVICE_TASKPRIORITIES_LED_STATUS        3  
#define DEVICE_TASKPRIORITIES_WIFI              8
#define DEVICE_TASKPRIORITIES_MQTT              6

#define DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS        2 
#define DEVICE_TASKPRIORITIES_RELAY_GREEN_ACTIVATE      DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS
#define DEVICE_TASKPRIORITIES_RELAY_ORANGE_ACTIVATE     DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS
#define DEVICE_TASKPRIORITIES_RELAY_RED_ACTIVATE        DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS
#define DEVICE_TASKPRIORITIES_RELAY_CANCEL_ACTIVATE     DEVICE_TASKPRIORITIES_RELAY_DATA_PROCESS 


#endif